/**
 * String Constants for BolicBuddy App
 * Organized by screen name for easy maintenance and localization
 */

export const STRINGS = {
  // Auth Screen
  AUTH: {
    signIn: "Sign In",
    signUp: "Sign Up",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    displayName: "Display Name",
    phoneNumber: "Phone Number (e.g., +1234567890)",
    verificationCode: "Enter 6-digit code",
    sendCode: "Send Verification Code",
    verifyCode: "Verify Code",
    login: "Login",
    register: "Register",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUpButton: "Sign Up",
    signInButton: "Sign In",
    createAccount: "Create Account",
    yourName: "Your Name",
    yourAge: "Your Age",
    age: "Age",
    trainingTypes: "Training Types",
    genderPreferences: "Gender & Preferences",
    yourGender: "Your Gender:",
    trainingPartnerPreference: "Training Partner Preference:",
    currentPRs: "Current PRs (Optional)",
    currentPRsPlaceholder: "e.g., Bench: 225lbs, Squat: 315lbs",
    next: "Next",
    back: "Back",
    finish: "Finish",
    sending: "Sending...",
    verifying: "Verifying...",
    resendCode: "Resend Code",
    steps: {
      step1: "Step 1 of 7",
      step2: "Step 2 of 7",
      step3: "Step 3 of 7",
      step4: "Step 4 of 7",
      step5: "Step 5 of 7",
      step6: "Step 6 of 7",
      step7: "Step 7 of 7",
    },
    labels: {
      verificationMessage: "We'll send a verification code to verify your phone number",
      enterCodeMessage: "Enter the 6-digit code sent to",
    },
    errors: {
      fillAllFields: "Please fill in all required fields",
      invalidEmail: "Please enter a valid email",
      passwordMismatch: "Passwords do not match",
      weakPassword: "Password must be at least 6 characters",
      failedToSend: "Failed to send verification code. Please try again.",
      enterCode: "Please enter the 6-digit verification code",
      invalidCode: "Invalid verification code. Please try again.",
      failedToVerify: "Failed to verify code. Please try again.",
    },
    success: {
      registered: "Account created successfully!",
      loggedIn: "Successfully signed in!",
      phoneVerified: "Phone number verified successfully!",
    },
  },

  // Chat Screen
  CHAT: {
    defaultTitle: "Chat",
    placeholder: "Type a message...",
    dateSeparators: {
      today: "Today",
      yesterday: "Yesterday",
    },
  },

  // Edit Profile Screen
  EDIT_PROFILE: {
    title: "Edit Profile",
    uploadNew: "Upload New ",
    updateDetails: "Update Personal Details",
    name: "Name",
    namePlaceholder: "Enter your name",
    location: "Location",
    locationPlaceholder: "Example Location",
    bio: "Bio",
    bioPlaceholder: "Share something about yourself...",
    saveChanges: "Save Changes",
  },

  // Home Screen
  HOME: {
    welcome: "Welcome",
    level: "Level",
    xp: "XP",
    weeklyGoal: "🎯 Weekly Goal",
    workoutOfDay: "🔥 Workout of the Day",
    recentAchievements: "🏆 Recent Achievements",
    quickNotes: "📝 Quick Notes",
    edit: "Edit",
    delete: "Delete",
    addNote: "Add a quick note...",
    startWorkout: "Start Workout",
    viewAll: "View All",
    deleteNoteTitle: "Delete Note",
    deleteNoteMessage: "Are you sure you want to delete this note?",
    cancel: "Cancel",
    workoutCompleted: "Workout Completed!",
    duration: "Duration",
    exercises: "Exercises",
    minutes: "min",
    achievements: {
      firstSteps: "First Steps",
      firstStepsDesc: "Complete your first workout",
      weekWarrior: "Week Warrior",
      weekWarriorDesc: "Workout 7 days in a row",
      socialButterfly: "Social Butterfly",
      socialButterflyDesc: "Connect with 5 training partners",
      strengthMaster: "Strength Master",
      strengthMasterDesc: "Complete 50 strength workouts",
    },
    difficultyLevels: {
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
    },
  },

  // Messages Screen
  MESSAGES: {
    title: "Messages",
    subtitle: "Chat with your training partners",
    search: "Search messages...",
    noMessages: "No messages yet",
    startConversation: "Start a new conversation",
    online: "Online",
    offline: "Offline",
    typing: "typing...",
    newMessage: "New Message",
    footer: "Real-time messaging coming soon!",
  },

  // Profile Screen
  PROFILE: {
    title: "Profile",
    edit: "Edit",
    stats: "Stats",
    achievements: "Achievements",
    workouts: "Workouts",
    friends: "Friends",
    posts: "Posts",
    following: "Following",
    followers: "Followers",
    logout: "Logout",
    about: "About",
    personalRecords: "Personal Records",
    trainingStyle: "Training Style",
    memberSince: "Member Since",
    viewProfile: "View Profile",
    guestUser: "Guest User",
    developmentUser: "Development User",
    defaultLocation: "San Francisco, CA",
    bio: "Fitness enthusiast on a mission to lift heavy and inspire others. Let's connect and crush some goals together! 🚀",
    tabs: {
      activity: "activity",
      achievements: "achievements",
    },
    subTabs: {
      posts: "posts",
      workouts: "workouts",
      connections: "connections",
    },
    statsLabels: {
      workouts: "WORKOUTS",
      streak: "STREAK",
      partners: "PARTNERS",
      awards: "AWARDS",
    },
    buttons: {
      follow: "Follow",
      following: "👤 Following",
      message: "Message",
      postIt: "Post it",
    },
    workoutCompleted: "Completed:",
  },

  // Settings Screen
  SETTINGS: {
    title: "Settings",
    notifications: "Notifications",
    enableNotifications: "Enable Notifications",
    profileVisibility: "Profile Visiblity",
    enablePublicProfile: "Enable Public Profile Visibility",
    matchingPreferences: "Matching Preferences",
    enablePreferences: "Enable Preferences?",
    deactivateAccount: "Deactivate Account?",
    account: "Account",
    privacy: "Privacy",
    help: "Help & Support",
    about: "About",
    logout: "Logout",
    version: "Version",
  },

  // Share Workout Screen
  SHARE_WORKOUT: {
    title: "Share Workout",
    subtitle: "Share your workout or achievement",
    whatsOnMind: "what's on your mind?",
    photoVideo: "Photo/Video",
    achievement: "Achievement",
    post: "Post",
    selectWorkout: "Select Workout",
    workoutDetails: "Workout Details",
    shareWith: "Share With",
    completed: "Completed:",
  },

  // Create Post Screen
  CREATE_POST: {
    title: "Create Post",
    subtitle: "Share your workout or achievement",
    caption: "Caption",
    captionPlaceholder: "What's on your mind?",
    selectImage: "Select Image",
    post: "Post",
    cancel: "Cancel",
    addTags: "Add Tags",
    addLocation: "Add Location",
    photoVideo: "Photo/Video",
    achievement: "Achievement",
    shareWorkout: "Share Workout?",
    achievementUnlocked: "ACHIEVEMENT UNLOCKED!",
    selectAchievement: "Select an Achievement",
    uploadedImage: "Uploaded Image",
    errors: {
      unableToOpenSettings: "Unable to open settings",
      addContent: "Please add some content to your post",
    },
    success: {
      postCreated: "Post created successfully!",
    },
  },

  // Find Screen
  FIND: {
    title: "Find Partners & Trainers",
    subtitle: "Swipe to discover",
    partners: "Partners",
    trainers: "Trainers",
    search: "Search...",
    filters: "Filters",
    distance: "Distance",
    trainingType: "Training Type",
    level: "Level",
    apply: "Apply",
    reset: "Reset",
    nearby: "Nearby",
    matchScore: "Match Score",
    away: "away",
    viewProfile: "View Profile",
    connect: "Connect",
    allCategories: "All Categories",
    selected: "selected",
    noMoreCardsTitle: "No More Cards",
    noMoreCardsText: "You've seen all available",
    forThisFilter: "for this filter.",
    progressOf: "of",
    skip: "Skip",
    alerts: {
      matchTitle: "Match! 🎉",
      bookTrainerTitle: "Book Trainer! 💪",
      matchMessage: "are a great match! Would you like to start a conversation?",
      bookTrainerMessage: "is available for training. Would you like to book a session?",
      notNow: "Not Now",
      rateExperience: "Rate Experience",
      startChat: "Start Chat",
      bookSession: "Book Session",
      bookingTitle: "Booking",
      bookingMessage: "Booking session with",
      ratingSubmittedTitle: "Rating Submitted! ⭐",
      ratingSubmittedMessage: "Thank you for rating",
      withStars: "with",
      stars: "stars!",
      youAnd: "You and",
      greatChoice: "Great choice!",
    },
  },

  // Workout Session Screen
  WORKOUT_SESSION: {
    title: "Workout Session",
    subtitle: "Edit workout session",
    subtitleNew: "Start new workout session",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    finish: "Finish",
    exercises: "Exercises",
    duration: "Duration",
    calories: "Calories",
    notes: "Notes",
    addExercise: "Add Exercise",
    sets: "Sets",
    reps: "Reps",
    weight: "Weight",
    rest: "Rest",
    completed: "Completed",
    inProgress: "In Progress",
    comingSoon: "Coming Soon!",
    description: "This screen will allow users to track their workouts, log exercises, sets, reps, and monitor their progress.",
  },

  // Forgot Password Screen
  FORGOT_PASSWORD: {
    title: "Forgot Password",
    email: "Email",
    emailPlaceholder: "Enter your email",
    emailAddress: "Email Address",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    sendResetLink: "Send Reset Link",
    backToLogin: "Back to Login",
    updatePassword: "Update Password",
    goToLogin: "Go to Login",
    resendEmail: "Resend Email",
    checkEmail: "Check your email",
    resetLinkSent: "We've sent a password reset link to your email address.",
    passwordUpdated: "Password updated successfully!",
    canLoginNow: "You can now login with your new password.",
    success: "Password reset link sent to your email",
    error: "Failed to send reset link",
    errors: {
      enterEmail: "Please enter your email address",
      validEmail: "Please enter a valid email address",
      enterNewPassword: "Please enter a new password",
      passwordLength: "Password must be at least 6 characters long",
      passwordMismatch: "Passwords do not match",
      failedToSend: "Failed to send reset link. Please try again.",
      failedToResend: "Failed to resend email. Please try again.",
      failedToUpdate: "Failed to update password. Please try again.",
    },
  },

  // Group Screens
  GROUPS: {
    title: "Groups",
    create: "Create Group",
    join: "Join",
    leave: "Leave",
    members: "Members",
    details: "Group Details",
    manage: "Manage Group",
    groupName: "Group Name",
    description: "Description",
    addMembers: "Add Members",
    save: "Save",
    myGroups: "My Groups",
    discover: "Discover Groups",
    admin: "Admin",
    member: "Member",
  },

  // Common
  COMMON: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    next: "Next",
    done: "Done",
    yes: "Yes",
    no: "No",
    ok: "OK",
    close: "Close",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    tryAgain: "Try Again",
    comingSoon: "Coming Soon",
    confirm: "Confirm",
    remove: "Remove",
    add: "Add",
    update: "Update",
    send: "Send",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    view: "View",
    share: "Share",
    like: "Like",
    comment: "Comment",
    reply: "Reply",
  },
};

export default STRINGS;
