
export const STRINGS = {
  appName: "Bolic",
  AUTH: {
    signIn: "Sign In",
    signUp: "Sign Up",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    displayName: "Display Name",
    phoneNumber: "Phone Number (e.g., +1234567890)",
    verificationCode: "Enter 6-digit code",
    sendCode: "Send Verification Code",
    verifyCode: "Verify Code",
    login: "Login",
    register: "Register",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUpButton: "Sign Up",
    signInButton: "Sign In",
    createAccount: "Create Account",
    yourName: "Your Name",
    yourAge: "Your Age",
    age: "Age",
    trainingTypes: "Training Types",
    genderPreferences: "Gender & Preferences",
    yourGender: "Your Gender:",
    trainingPartnerPreference: "Training Partner Preference:",
    currentPRs: "Current PRs (Optional)",
    currentPRsPlaceholder: "e.g., Bench: 225lbs, Squat: 315lbs",
    next: "Next",
    back: "Back",
    finish: "Finish",
    sending: "Sending...",
    verifying: "Verifying...",
    resendCode: "Resend Code",
    steps: {
      step1: "Step 1 of 7",
      step2: "Step 2 of 7",
      step3: "Step 3 of 7",
      step4: "Step 4 of 7",
      step5: "Step 5 of 7",
      step6: "Step 6 of 7",
      step7: "Step 7 of 7",
    },
    labels: {
      verificationMessage:
        "We'll send a verification code to verify your phone number",
      enterCodeMessage: "Enter the 6-digit code sent to",
    },
    errors: {
      fillAllFields: "Please fill in all required fields",
      invalidEmail: "Please enter a valid email",
      passwordMismatch: "Passwords do not match",
      weakPassword: "Password must be at least 6 characters",
      failedToSend: "Failed to send verification code. Please try again.",
      enterCode: "Please enter the 6-digit verification code",
      invalidCode: "Invalid verification code. Please try again.",
      failedToVerify: "Failed to verify code. Please try again.",
    },
    success: {
      registered: "Account created successfully!",
      loggedIn: "Successfully signed in!",
      phoneVerified: "Phone number verified successfully!",
    },
  },

  CHAT: {
    defaultTitle: "Chat",
    placeholder: "Type a message...",
    dateSeparators: {
      today: "Today",
      yesterday: "Yesterday",
    },
  },

  EDIT_PROFILE: {
    title: "Edit Profile",
    uploadNew: "Upload New ",
    updateDetails: "Update Personal Details",
    name: "Name",
    namePlaceholder: "Enter your name",
    location: "Location",
    locationPlaceholder: "Example Location",
    bio: "Bio",
    bioPlaceholder: "Share something about yourself...",
    saveChanges: "Save Changes",
  },

  HOME: {
    welcome: "Welcome",
    level: "Level",
    xp: "XP",
    weeklyGoal: "Weekly Goal",
    workoutOfDay: "Workout of the Day",
    recentAchievements: "Recent Achievements",
    quickNotes: "Quick Notes",
    edit: "Edit",
    delete: "Delete",
    addNote: "Add a quick note...",
    startWorkout: "Start Workout",
    viewAll: "View All",
    deleteNoteTitle: "Delete Note",
    deleteNoteMessage: "Are you sure you want to delete this note?",
    cancel: "Cancel",
    workoutCompleted: "Workout Completed!",
    duration: "Duration",
    exercises: "Exercises",
    minutes: "min",
    achievements: {
      firstSteps: "First Steps",
      firstStepsDesc: "Complete your first workout",
      weekWarrior: "Week Warrior",
      weekWarriorDesc: "Workout 7 days in a row",
      socialButterfly: "Social Butterfly",
      socialButterflyDesc: "Connect with 5 training partners",
      strengthMaster: "Strength Master",
      strengthMasterDesc: "Complete 50 strength workouts",
    },
    difficultyLevels: {
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
    },
  },

  MESSAGES: {
    title: "Messages",
    subtitle: "Chat with your training partners",
    search: "Search messages...",
    noMessages: "No messages yet",
    startConversation: "Start a new conversation",
    online: "Online",
    offline: "Offline",
    typing: "typing...",
    newMessage: "New Message",
    footer: "Real-time messaging coming soon!",
    groupFallback: "Group conversation",
    partnerFallback: "Training partner",
    attachmentPlaceholder: "Sent an attachment",
    noMessagesYet: "No messages yet",
    youLabel: "You:",
    emptyTitle: "Start the conversation",
    emptySubtitle: "Connect with training partners to see your chats here.",
  },

  PROFILE: {
    title: "Profile",
    edit: "Edit",
    stats: "Stats",
    achievements: "Achievements",
    workouts: "Workouts",
    friends: "Friends",
    posts: "Posts",
    following: "Following",
    followers: "Followers",
    logout: "Logout",
    about: "About",
    personalRecords: "Personal Records",
    trainingStyle: "Training Style",
    memberSince: "Member Since",
    viewProfile: "View Profile",
    guestUser: "Guest User",
    developmentUser: "Development User",
    tabs: {
      activity: "activity",
      achievements: "achievements",
    },
    subTabs: {
      posts: "posts",
      workouts: "workouts",
      connections: "connections",
    },
    statsLabels: {
      workouts: "WORKOUTS",
      streak: "STREAK",
      partners: "PARTNERS",
      awards: "AWARDS",
    },
    buttons: {
      follow: "Follow",
      following: "👤 Following",
      message: "Message",
      postIt: "Post it",
    },
    workoutCompleted: "Completed:",
  },

  SETTINGS: {
    title: "Settings",
    notifications: "Notifications",
    enableNotifications: "Enable Notifications",
    profileVisibility: "Profile Visiblity",
    enablePublicProfile: "Enable Public Profile Visibility",
    matchingPreferences: "Matching Preferences",
    enablePreferences: "Enable Preferences?",
    deactivateAccount: "Deactivate Account?",
    saving: "Saving",
    updateSuccess: "Settings updated",
    updateError: "Unable to update settings",
    confirmDeactivateTitle: "Deactivate Account",
    confirmDeactivateMessage:
      "Are you sure you want to deactivate your account? You can log in again to reactivate it.",
    confirmDeactivateConfirm: "Yes, deactivate",
    confirmDeactivateCancel: "Cancel",
    deleteSuccess: "Your account has been deactivated",
    deleteError: "Failed to deactivate account",
    account: "Account",
    privacy: "Privacy",
    help: "Help & Support",
    about: "About",
    logout: "Logout",
    version: "Version",
    aboutApp: "About Bolic",
    appVersion: "App Version",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    linkUnavailable: "Not available yet",
    updateNotPersisted: "The server didn't save that change",
    // The server ignores an empty `trainingTypes` array, so the last style
    // cannot be removed. See BACKEND-ASK.md item 65.
    keepOneTrainingStyle: "Keep at least one training style — your profile needs one to match you with anybody.",
    linkOpenError: "Couldn't open that link",
    notificationsDeliveryNote:
      "Saves your preference and your device permission. The server does not deliver push notifications yet.",
    notificationsBlocked: "Notifications are blocked in your device settings",
    notificationsPermissionRequired:
      "Allow notifications in your device settings to turn this on",
    openSystemSettings: "Open device settings",
    matchingPreferencesHint: "Pick the training styles you want to be matched on",
  },

  SHARE_WORKOUT: {
    title: "Share Workout",
    subtitle: "Share your workout or achievement",
    whatsOnMind: "what's on your mind?",
    photoVideo: "Photo/Video",
    achievement: "Achievement",
    post: "Post",
    selectWorkout: "Select Workout",
    workoutDetails: "Workout Details",
    shareWith: "Share With",
    completed: "Completed:",
  },

  CREATE_POST: {
    title: "Create Post",
    subtitle: "Share your workout or achievement",
    caption: "Caption",
    captionPlaceholder: "What's on your mind?",
    selectImage: "Select Image",
    post: "Post",
    cancel: "Cancel",
    addTags: "Add Tags",
    addLocation: "Add Location",
    photoVideo: "Photo/Video",
    achievement: "Achievement",
    shareWorkout: "Share Workout?",
    achievementUnlocked: "ACHIEVEMENT UNLOCKED!",
    selectAchievement: "Select an Achievement",
    uploadedImage: "Uploaded Image",
    shareToCommunity: "Share also on community highlights?",
    errors: {
      unableToOpenSettings: "Unable to open settings",
      addContent: "Please add some content to your post",
    },
    success: {
      postCreated: "Post created successfully!",
    },
  },

  FIND: {
    title: "Find Partners & Trainers",
    subtitle: "Swipe to discover",
    partners: "Partners",
    trainers: "Trainers",
    search: "Search...",
    filters: "Filters",
    distance: "Distance",
    trainingType: "Training Type",
    level: "Level",
    apply: "Apply",
    reset: "Reset",
    nearby: "Nearby",
    matchScore: "Match Score",
    away: "away",
    viewProfile: "View Profile",
    connect: "Connect",
    allCategories: "All Categories",
    selected: "selected",
    noMoreCardsTitle: "No More Cards",
    noMoreCardsText: "You've seen all available",
    forThisFilter: "for this filter.",
    progressOf: "of",
    skip: "Skip Profile",
    alerts: {
      matchTitle: "Match! 🎉",
      bookTrainerTitle: "Book Trainer! 💪",
      matchMessage:
        "are a great match! Would you like to start a conversation?",
      bookTrainerMessage:
        "is available for training. Would you like to book a session?",
      notNow: "Not Now",
      rateExperience: "Rate Experience",
      startChat: "Start Chat",
      bookSession: "Book Session",
      bookingTitle: "Booking",
      bookingMessage: "Booking session with",
      youAnd: "You and",
      greatChoice: "Great choice!",
    },
  },

  WORKOUT_SESSION: {
    title: "Workout Session",
    subtitle: "Edit workout session",
    subtitleNew: "Start new workout session",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    finish: "Finish",
    exercises: "Exercises",
    duration: "Duration",
    notes: "Notes",
    addExercise: "Add Exercise",
    sets: "Sets",
    reps: "Reps",
    weight: "Weight",
    rest: "Rest",
    completed: "Completed",
    inProgress: "In Progress",
    comingSoon: "Coming Soon!",
    description:
      "This screen will allow users to track their workouts, log exercises, sets, reps, and monitor their progress.",
  },

  WORKOUT_HISTORY: {
    title: "Workout History",
    subtitle: "View / Manage your workout history",
    startNew: "Start New Workout",
    postIt: "Post it",
    completed: "Completed:",
    loadFailed: "Failed to load workout history",
    retry: "Retry",
    emptyTitle: "No workout history yet",
    emptySubtitle: "Complete your first workout to see it here!",
    viewDetails: "Exercise details",
    hideDetails: "Hide details",
    loggedSets: "Logged sets",
    plannedExercises: "Workout plan",
    noExerciseDetail:
      "Exercise details aren't available for this session yet.",
    setLabel: "Set",
    setsSuffix: "sets",
    exercisesSuffix: "exercises",
    sharePrefillCaption: "Just finished",
  },

  FORGOT_PASSWORD: {
    title: "Forgot Password",
    email: "Email",
    emailPlaceholder: "Enter your email",
    emailAddress: "Email Address",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    sendResetLink: "Send Reset Link",
    backToLogin: "Back to Login",
    updatePassword: "Update Password",
    goToLogin: "Go to Login",
    resendEmail: "Resend Email",
    checkEmail: "Check your email",
    resetLinkSent: "We've sent a password reset link to your email address.",
    passwordUpdated: "Password updated successfully!",
    canLoginNow: "You can now login with your new password.",
    success: "Password reset link sent to your email",
    error: "Failed to send reset link",
    errors: {
      enterEmail: "Please enter your email address",
      validEmail: "Please enter a valid email address",
      enterNewPassword: "Please enter a new password",
      passwordLength: "Password must be at least 6 characters long",
      passwordMismatch: "Passwords do not match",
      failedToSend: "Failed to send reset link. Please try again.",
      failedToResend: "Failed to resend email. Please try again.",
      failedToUpdate: "Failed to update password. Please try again.",
    },
  },

  GROUPS: {
    title: "Groups",
    subtitle: "Join gym and training groups",
    create: "Create Group",
    join: "Join",
    leave: "Leave",
    members: "Members",
    details: "Group Details",
    manage: "Manage Group",
    groupName: "Group Name",
    description: "Description",
    addMembers: "Add Members",
    save: "Save",
    myGroups: "My Groups",
    discover: "Discover Groups",
    admin: "Admin",
    member: "Member",
  },

  BOOKING_CONFIRMATION: {
    title: "Confirm Your Session",
    subtitle: "Go through before you finalize",
    infoCards: {
      trainer: "Trainer",
      dateTime: "Date & Time",
      location: "Location",
      session: "Session",
    },
    fallbacks: {
      trainer: "Trainer",
      session: "Training Session",
      location: "Location to be confirmed",
    },
    cancellationPolicy: {
      title: "Cancellation Policy",
      description:
        "In the event of session cancellation, a processing fee of 3% will be deducted from the refund amount. The remaining balance will be returned to your original payment method within 5-7 business days.",
      processingFee: "3%",
      refundTimeline: "5-7 business days",
      details: [
        "Applies to cancellations by both clients and trainers",
        "No refund within 2 hours of session start time",
      ],
    },
    buttons: {
      proceedToPayment: "Proceed to Payment",
      processing: "Processing...",
    },
    messages: {
      goingBack: "Going back to session selection",
      paymentSuccess: "Payment successful! Your session is booked.",
      bookingFailed: "Failed to create booking. Please try again.",
      paidButNotBooked:
        "Your payment went through, but the session could not be created. Do not pay again — contact support and we will book it or refund you.",
      paidPartiallyBooked:
        "Your payment went through, but not every slot could be booked. Check My Bookings before trying again.",
      paymentError: "Failed to process payment. Please try again.",
      paymentCancelled: "Payment Cancelled",
    },
    errors: {
      bookingFailed: "Failed to create booking. Please try again.",
      paymentError: "Failed to process payment. Please try again.",
      dateConversionError: "Failed to convert date/time to UTC",
      missingPrice:
        "This session package is missing. Go back and pick a package again.",
    },
  },

  SCHEDULED_SESSIONS: {
    title: "Scheduled Sessions",
    subtitle: "Your upcoming sessions with trainers",
    bookNewSession: "Book New Session",
    noUpcomingSessions: "No upcoming sessions",
    reschedule: "Reschedule",
    cancel: "Cancel",
    with: "with",
    messages: {
      sessionCancelled: "Session cancelled successfully",
      cancellationFailed: "Failed to cancel session",
      refundFailed:
        "Session cancelled, but the refund could not be started. Please contact support.",
    },
    cancellationModal: {
      title: "Cancel Session",
      subtitle:
        "Are you sure you want to cancel this session?",
      paymentSummary: "Payment",
      refundTerms: "Refund Breakdown",
      refundLabels: {
        sessionAmount: "Amount Paid:",
        processingFee: "Processing Fee:",
        refundableAmount: "Refund Amount:",
        expectedArrival: "Expected Arrival:",
      },
      refundPending:
        "Your refund amount and arrival date are confirmed by the payment provider after the session is cancelled.",
      confirmButton: "Confirm Cancellation",
    },
  },

  SELECT_DATE_TIME: {
    availableSlots: "Available Slots",
    firstAvailable: "First available",
    loadingAvailability: "Loading availability...",
    noSlotsToday: "No slots left today",
    notAvailable: "Not available",
    missingTrainer: "Select a trainer to see their availability.",
    availabilityError: "Could not load availability. Pull to refresh or try again.",
    noAvailability: "No availability published yet",
    noAvailabilityHint:
      "This trainer has not opened any slots. Check back later or message them.",
  },

  COMMON: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    next: "Next",
    done: "Done",
    yes: "Yes",
    no: "No",
    ok: "OK",
    close: "Close",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    tryAgain: "Try Again",
    comingSoon: "Coming Soon",
    confirm: "Confirm",
    remove: "Remove",
    add: "Add",
    update: "Update",
    send: "Send",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    view: "View",
    share: "Share",
    like: "Like",
    comment: "Comment",
    reply: "Reply",
  },

  WEEKLY_GOAL: {
    createTitle: "Create Weekly Goal",
    editTitle: "Edit Weekly Goal",
    createSubtitle: "Set a target for this week",
    editSubtitle: "Adjust your target for this week",
    targetLabel: "Weekly target",
    titleLabel: "Goal name",
    titlePlaceholder: "Complete 4 Workouts This Week",
    save: "Save Goal",
    saving: "Saving...",
    remove: "Remove Goal",
    createButton: "Create Weekly Goal",
    emptyTitle: "No weekly goal set",
    emptySubtitle: "Set a target and track it here each week.",
    units: {
      workouts: "workouts",
    },
    errors: {
      invalidTarget: "Enter a target greater than zero",
    },
    saved: "Weekly goal saved",
    removed: "Weekly goal removed",
  },

  RATING: {
    modalTitle: "Leave a Rating",
    modalTitleEdit: "Update Your Rating",
    submitEdit: "Update Rating",
    updated: "Your rating was updated",
    rateButtonEdit: "Update Your Rating",
    yourRating: "Your rating",
    loadMore: "Load More",
    loading: "Loading ratings...",
    reviewsSuffix: "Reviews",
    reviewSuffix: "Review",
    noComment: "No comment left",
    loadFailed: "Could not load ratings",
    retry: "Try Again",
    trainerSubtitle: "How was your session with this trainer?",
    partnerSubtitle: "How was training with this partner?",
    genericSubtitle: "How was your experience?",
    commentLabel: "Add a comment",
    commentPlaceholder: "Share what went well, or what could be better...",
    submit: "Submit Rating",
    submitting: "Submitting...",
    starLabels: {
      1: "Poor",
      2: "Fair",
      3: "Good",
      4: "Great",
      5: "Excellent",
    },
    tapToRate: "Tap a star to rate",
    errors: {
      noStars: "Pick a star rating before submitting",
      failed: "Could not submit your rating. Please try again.",
    },
    success: "Thanks for your rating",
    rateButton: "Leave a Rating",
    myRatingsMenu: "My Ratings",
    userRatingsMenu: "Ratings",
    emptyTitle: "No ratings yet",
    emptySubtitle: "Ratings appear here once someone you have trained with leaves one.",
  },

  ACHIEVEMENTS: {
    title: "Achievements",
    titleOther: "User Achievements",
    subtitle: "Track your achievements",
    subtitleOther: "View user achievements",
    bookSession: "Book New Session",
    loading: "Loading achievements...",
    loadFailed: "Failed to load achievements.",
    empty: "No achievements yet.",
    emptyOther: "This user has no achievements yet.",
    earnedSection: "Earned",
    lockedSection: "Locked",
    summary: (earned: number, total: number) => `${earned} of ${total} unlocked`,
    earnedCount: (earned: number) =>
      `${earned} ${earned === 1 ? "achievement" : "achievements"} earned`,
    earnedOn: (date: string) => `Earned ${date}`,
    earnedLabel: "Earned",
    lockedLabel: "Locked",
    progressLabel: (progress: number, target: number) => `${progress}/${target}`,
    catalogueUnavailable:
      "Locked achievements are unavailable right now, so only earned ones are shown.",
    noProgressData: "Progress not tracked yet",
  },
};

export default STRINGS;
